--- #YAML:1.0
name:               Music-Tag-M4A
version:            0.4001
abstract:           Plugin module for Music::Tag to get information from Apple QuickTime headers. 
author:
    - Edward Allen (ealleniii _at_ cpan _dot_ org)
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Audio::M4P::QuickTime:  0.37
    MP4::Info:            1.12
    Music::Tag:           0.4001
    Tree::Simple:         0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
